name: üöÄ .NET Core API CI/CD

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: Lynkr-API
  DOTNET_VERSION: 8.0.x
  API_PROJECT_PATH: Backend/backend/Lynkr/Lynkr.csproj
  TEST_PROJECT_PATH: Backend/backend/Lynkr.Tests/Lynkr.Tests.csproj
  DB_CONTEXT_PROJECT: Backend/backend/Lynkr/Lynkr.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore Backend/backend/backend.sln

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Build and Publish API Artifact
      run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release -o ./myapp


    - name: ‚¨ÜÔ∏è Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        package: ./myapp

